apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod
spec:
  containers:
    - name: todoapp
      image: manojofficialmj/todoapp:32094c46cca4e498a1756a6b2c56a378ee7a728d
      ports:
        - containerPort: 80
